/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIAPI_JniSerialPort */

#ifndef _Included_JNIAPI_JniSerialPort
#define _Included_JNIAPI_JniSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIAPI_JniSerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_JNIAPI_JniSerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     JNIAPI_JniSerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIAPI_JniSerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
